version: "3"
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.2
    container_name: etcd
    restart: always
    ports:
      - "12379:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_NAME=etcd
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCDCTL_API=3
      - ETCD_LOGGER=zap
      - ETCD_DATA_DIR=/etcd-data
    volumes:
      - "/etcd-data:/etcd-data"
      - "/etc/localtime:/etc/localtime:ro"